spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: docker
    password: mysql
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update